### PR TITLE
Update AST node names to match ESTree [breaking change]

### PR DESCRIPTION
**Pull request by tchetwin**
PrivateName -> PrivateIdentifier
privateNameToken -> privateIdentifierToken

This follows https://github.com/acornjs/acorn-private-class-elements/pull/16 and precedes a update to acorn-stage3.

### CODE REVIEW

**Comment by adrianheine** [comment]
This produces test failures for me.

**Comment by tchetwin** [comment]
rm'd `node_modules/`, re-`npm i`'d:

### `npm t`
<details><summary>Output</summary>
<p>

```
$ npm t

> acorn-private-methods@1.0.0 test
> mocha



  acorn-private-methods
    ✓ class A { a() { this.#a }; #a() {} }
    ✓ var C = class {
  #m() { return 42; }
  constructor() {
    (() => this)().#m
  }
}
    ✓ class A { #a() {}; f() { delete this.#a } }
    ✓ class A { #a() {}; #a() {} }
    ✓ class A { get #a() {}; set #a(newA) {} }
    ✓ class A { a() { this.#a } }
    ✓ class A { a() { this.#a } b() { this.#b } }
    ✓ class A { #constructor() {} }
    ✓ class A { #[ab]() {} }
    ✓ a = { #ab() {} }
    ✓ class A { [{#ab() {}}]() {} }
    ✓ class A{ # a() {}}
    ✓ class C{ #method() { super(); } };
    ✓ class C{ #method() { super.y(); } };
    ✓ class A { #x() {} }
    ✓ class A { #x() {}; }
    ✓ class A { #x() {}; #y() {} }
    ✓ class A { #x() {};a() {} }
    ✓ class A { #x() {}
a() {} }
    ✓ class A { get #x() {} }
    ✓ class A { get #x() {}; }
    ✓ class A { get #x() {}; #y() {} }
    ✓ class A { get #x() {};a() {} }
    ✓ class A { get #x() {}
a() {} }
    ✓ class C { \u0061sync m(){} };
    ✓ class A extends B { constructor() { super() } }
    ✓ class X { static #private() {} }


  27 passing (23ms)
```

</p>
</details>

### `npm run test:test262`

<details><summary>Output</summary>
<p>

```
$ npm run test:test262

> acorn-private-methods@1.0.0 test:test262
> node run_test262.js

Testing complete.
Summary:
 ✔ 1965 valid programs parsed without error
 ✔ 340 invalid programs produced a parsing error
 ✔ 0 invalid programs did not produce a parsing error (and allowed by the whitelist file)
 ✔ 0 valid programs produced a parsing error (and allowed by the whitelist file)
 ✔ 72022 programs were skipped
```

</p>
</details>

---

Which tests do you see failing?

**Comment by adrianheine** [comment]
I forgot to build oO

**Comment by tchetwin** [comment]
> I forgot to build oO

We could add:

```
    "pretest": "npm run build",
```

Not sure if there's an `npm`/`yarn` agnostic way to run one run-script from another.

**Pull request merged**
